name: First Workflow

on: workflow_dispatch  # Event to trigger the workflow

jobs:
  first-job:
    runs-on: ubuntu-latest  # Fixed: 'runs-on' instead of 'runs on'
    
    steps:
      - name: Print greeting
        run: echo "Welcome to GitHub Workflow"
      
      - name: Display files
        run: ls -ltr
      
      - name: Print bye
        run: echo "Bye from GitHub Actions"

      
